#!/usr/bin/python
#########################################################
# initDisplay() - called to initialise the display
# lcdClear() - called to clear the display
# lcdShowLogo() - show Pi Logo
# lcdDisplay() - called after any changes to render display
# lcdDisplayText(int x, int y, str s, int colour)
# lcdDrawRect(int x0, int y0, int x1, int y1, int colour)
# lcdFillRect(int x0, int y0, int x1, int y1, int colour)
# lcdDrawLine(int x0, int y0, int x1, int y1, int colour)
# lcdDrawCircle(int x, int y, int, rad, int colour)
# lcdFillCircle(int x, int y, int, rad, int colour)
# lcdSetPixel(int x, int y, int colour)
# lcdGetPixel(int x, int y) returns int
# lcdSetTextColour(int colour)
# lcdSetTextSize(int size)
# lcdSetContrast(int contrast)
# lcdSetCursor(int x, int y)
#########################################################

import sys,time
sys.path.append('/usr/local/lib/lcd')
from lcd import *

print "Result from initDisplay:", initDisplay()
#A=0
#while A < 254:
#	A=A+1
#	lcdDisplayText(0,0,chr(A)+chr(A)+chr(A)+chr(A))
#	lcdDisplayText(0,8,chr(A)+chr(A)+chr(A)+chr(A))
#	lcdDisplay()
#	time.sleep(1.0)
lcdShowLogo()
time.sleep(1.0)
lcdDrawRect(0,0,84,48,1)
lcdDisplay()
time.sleep(0.1)
lcdDrawRect(0,0,84,48,0)
lcdDisplay()
time.sleep(0.1)
lcdDrawRect(0,0,84,48,1)
lcdDisplay()
time.sleep(0.1)
lcdDrawRect(0,0,84,48,0)
lcdDisplay()
time.sleep(0.1)
lcdDrawRect(0,0,84,48,1)
lcdDisplay()
time.sleep(0.1)
lcdFillRect(0,0,84,48,1)
lcdDisplay()
time.sleep(2.1)
lcdClear()
lcdDisplay()
print "Initial Value :", lcdGetPixel(10,10)
lcdSetPixel(10,10,1)
print "Value before display :", lcdGetPixel(10,10)
lcdDisplay()
print "Value after display :", lcdGetPixel(10,10)
time.sleep(0.1)
print "Loopit"
lcdSetTextColour(1)
lcdDrawCircle(60,24,20,1)
while True:
	lcdFillCircle(60,24,20,0)
	lcdDrawCircle(60,24,20,1)
	lcdSetTextColour(1)
	lcdDisplayText(0,0,"Line 1")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,8,"Line 2")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,16,"Line 3")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,24,"Line 4")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,32,"Line 5")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,40,"Line 6")
	lcdDisplay()
        time.sleep(0.05)
	lcdSetTextColour(0)
	lcdDisplayText(0,40,"Line 6")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,32,"Line 5")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,24,"Line 4")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,16,"Line 3")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,8,"Line 2")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,0,"Line 1")
	lcdDisplay()
        time.sleep(0.05)
	lcdFillCircle(60,24,20,1)
	lcdSetTextColour(1)
	lcdDisplayText(0,40,"Line 6")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,32,"Line 5")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,24,"Line 4")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,16,"Line 3")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,8,"Line 2")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,0,"Line 1")
	lcdDisplay()
        time.sleep(0.05)
	lcdSetTextColour(0)
	lcdDisplayText(0,0,"Line 1")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,8,"Line 2")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,16,"Line 3")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,24,"Line 4")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,32,"Line 5")
	lcdDisplay()
        time.sleep(0.05)
	lcdDisplayText(0,40,"Line 6")
	lcdDisplay()
        time.sleep(0.05)
